AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploy a PostgreSQL RDS instance for the ChemTrack application,
  including networking, subnet group, parameter group, and security.

Parameters:
  AppName:
    Type: String
    Default: chemtrack
    Description: Application name (will prefix resource names)

  VpcId:
    Type: String
    Default: vpc-019e35a7f8ca205e5
    Description: VPC ID for deployment

  PrivateSubnet1:
    Type: String
    Default: subnet-08de8ae010ebfa1f3
    Description: First private subnet

  PrivateSubnet2:
    Type: String
    Default: subnet-0205ddf1053073b5c
    Description: Second private subnet

  DBInstanceClass:
    Type: String
    Default: db.t4g.medium
    Description: RDS instance class
    AllowedValues:
      - db.t4g.medium
      - db.t4g.large
      - db.r6g.large

  BackupRetentionPeriod:
    Type: Number
    Default: 14
    MinValue: 1
    MaxValue: 35
    Description: Days to retain automated backups

  PreferredBackupWindow:
    Type: String
    Default: "22:00-22:59"
    Description: Daily backup window

  PreferredMaintenanceWindow:
    Type: String
    Default: "sat:23:00-sat:23:59"
    Description: Weekly maintenance window

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PostgreSQL access security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/8
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-db-sg"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-db-subnet-group"

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
