# Specifies the version of the CloudFormation template language
AWSTemplateFormatVersion: '2010-09-09'

# Description shown in the CloudFormation console
Description: 'CloudFormation template for ChemTrack Database Network Load Balancer’

# Input parameters users can override when creating the stack
Parameters:
  # Application name — used for consistent resource naming
  AppName:
    Type: String
    Description: Name of the application
    Default: chemtrack

  # VPC where the NLB will reside
  VpcId:
    Type: String
    Description: VPC ID where the NLB will be deployed
    Default: vpc-019e35a7f8ca205e5

  # First intranet subnet for the NLB
  IntranetSubnet1:
    Type: String
    Description: First intranet subnet ID for the NLB
    Default: subnet-0ee959776d1683aa5

  # Second intranet subnet for the NLB
  IntranetSubnet2:
    Type: String
    Description: Second intranet subnet ID for the NLB
    Default: subnet-07257f93f815ce77c

  # IP address of the database (for target group)
  DatabaseIP:
    Type: String
    Description: IP address of the database for the target group
    Default: ''

# The AWS resources that will be created
Resources:
  # Network Load Balancer for the database traffic
  DatabaseNLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      # Name uses the AppName parameter
      Name: !Sub ${AppName}-db-nlb
      Type: network
      Scheme: internal
      Subnets:
        - !Ref IntranetSubnet1
        - !Ref IntranetSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-db-nlb

  # Target group to point to the database instance
  DatabaseTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AppName}-db-tg
      Port: 5432
      Protocol: TCP
      VpcId: !Ref VpcId
      TargetType: ip
      Targets:
        - Id: !Ref DatabaseIP
          Port: 5432
      HealthCheckEnabled: true
      HealthCheckPort: 5432
