AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for ChemTrack Search Container'

Parameters:
  AppName:
    Type: String
    Description: Name of the application
    Default: chemtrack
  AppURL:
    Type: String
    Description: root application url
    Default: "chemtrack.767397980456.aws.glpoly.net"
  VpcId:
    Type: String
    Description: VPC ID where the ECS cluster will be deployed
    Default: vpc-019e35a7f8ca205e5
  PrivateSubnet1:
    Type: String
    Description: First private subnet ID for the ECS cluster
    Default: subnet-08de8ae010ebfa1f3
  PrivateSubnet2:
    Type: String
    Description: Second private subnet ID for the ECS cluster
    Default: subnet-0205ddf1053073b5c

Resources:
  # CloudWatch Log Group
  SearchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AppName}-search
      RetentionInDays: 7

  # Target Group
  SearchTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AppName}-search-tg
      Port: 8000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-search-tg

  # ALB Rule
  SearchRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue chemtrack-https-listener-arn
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values:
            - /search*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref SearchTargetGroup

  # ECS Task Definition
  SearchTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-search
      Cpu: '1024'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue chemtrack-ecs-task-execution-role-arn
      TaskRoleArn: !ImportValue chemtrack-ecs-task-role-arn
      ContainerDefinitions:
        - Name: !Sub ${AppName}-search-container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/chemtrack/search:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8000
              HostPort: 8000
              Protocol: tcp
          Environment:
            - Name: BASE_URL
              Value: !Ref AppURL
            - Name: SECRET_KEY
              Value: '64df77320c1b5b56396028e0dfc01deb'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref SearchLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-search-task

  # ECS Service
  SearchService:
    Type: AWS::ECS::Service
    DependsOn: SearchRule
    Properties:
      ServiceName: !Sub ${AppName}-search-service
      Cluster: !ImportValue chemtrack-cluster-arn
      TaskDefinition: !Ref SearchTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !ImportValue chemtrack-ecs-security-group-id
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      LoadBalancers:
        - ContainerName: !Sub ${AppName}-search-container
          ContainerPort: 8000
          TargetGroupArn: !Ref SearchTargetGroup
      HealthCheckGracePeriodSeconds: 60
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-search-service
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !Sub ${AppName}.local

Outputs:
  SearchServiceArn:
    Description: The ARN of the Search ECS service
    Value: !Ref SearchService
    Export:
      Name: !Sub ${AppName}-search-service-arn

  SearchTaskDefinitionArn:
    Description: The ARN of the Search Task Definition
    Value: !Ref SearchTaskDefinition
    Export:
      Name: !Sub ${AppName}-search-task-definition-arn

  SearchTargetGroupArn:
    Description: The ARN of the Search Target Group
    Value: !Ref SearchTargetGroup
    Export:
      Name: !Sub ${AppName}-search-target-group-arn
